// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	PACKING_SYNC_DO?: DurableObjectNamespace;
	NEXTJS_ENV?: string;
	NEXT_PUBLIC_GOOGLE_MAPS_API_KEY?: string;
	GOOGLE_MAPS_API_KEY?: string;
}
