-- Einmalig ausführen, wenn Schema schon manuell angewendet wurde, d1_migrations aber leer ist.
-- Danach: npx wrangler d1 migrations list camping-db --remote  → sollte leer sein.
-- NICHT in migrations/ ablegen – Wrangler würde es sonst als neue Migration behandeln.

INSERT INTO d1_migrations (name) VALUES
  ('0001_initial.sql'),
  ('0002_transport_mitreisenden.sql'),
  ('0002_transport_mitreisenden_v2.sql'),
  ('0003_anzahl_per_mitreisender.sql'),
  ('0004_erst_abreisetag_gepackt.sql'),
  ('0005_mitreisende_farbe.sql'),
  ('0006_transportmittel_festgewicht.sql'),
  ('0007_add_pauschalgewicht.sql'),
  ('0008_auth_system.sql'),
  ('0009_einladungen_admin.sql'),
  ('0010_mitreisender_transport.sql'),
  ('0011_must_change_password.sql'),
  ('0012_temporary_packlist_entries.sql'),
  ('0013_campingplaetze_and_routes.sql'),
  ('0014_campingplaetze_photo.sql'),
  ('0015_urlaub_campingplaetze_sort_index.sql'),
  ('0016_packliste_default_ansicht.sql'),
  ('0017_tag_kategorien.sql'),
  ('0018_checklisten.sql'),
  ('0019_campingplatz_fotos.sql'),
  ('0020_mengenregel.sql'),
  ('0021_campingplaetze_wunschliste_top.sql'),
  ('0022_transportmittel_icon.sql'),
  ('0023_transportmittel_icon_data.sql'),
  ('0024_integrations.sql'),
  ('0025_urlaub_campingplaetze_dauer.sql'),
  ('0026_mitreisende_spalten.sql'),
  ('0026_mitreisenden_gruppen_rollen.sql'),
  ('0026_users_einladungen_rollen.sql'),
  ('0027_pauschal_gruppen.sql'),
  ('0028_packliste_gewicht_override.sql'),
  ('0029_person_gewicht_override.sql'),
  ('0030_rastplaetze.sql'),
  ('0031_push_subscriptions.sql'),
  ('0032_user_push_preferences.sql'),
  ('0033_user_reise_gps_mode.sql'),
  ('add_tags_system.sql');
